apiVersion: v1
kind: ServiceAccount
metadata:
  name: htpasswd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour:authserver:htpasswd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contour:authserver:htpasswd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour:authserver:htpasswd
subjects:
- kind: ServiceAccount
  name: htpasswd
  namespace: dev141
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: htpasswd
  name: htpasswd
spec:
  ports:
  - name: auth
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: htpasswd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: htpasswd
  name: htpasswd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: htpasswd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: htpasswd
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # - htpasswd
      - args:
        - testserver
        - --address=:9443
        - --tls-ca-path=/tls/ca.crt
        - --tls-cert-path=/tls/tls.crt
        - --tls-key-path=/tls/tls.key
        command:
        - /contour-authserver
        image: venafidevops/sandbox:envoy-authserver
        imagePullPolicy: Always
        # image: docker.io/projectcontour/contour-authserver:v3
        # imagePullPolicy: IfNotPresent
        name: htpasswd
        ports:
        - containerPort: 9443
          name: auth
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 5Gi
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
      serviceAccountName: htpasswd
      volumes:
      - name: tls
        secret:
          secretName: htpasswd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: htpasswd
spec:
  dnsNames:
  - htpasswd
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  secretName: htpasswd
---
apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  name: htpasswd
spec:
  protocol: h2
  services:
  - name: htpasswd
    port: 9443